#!/bin/sh

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# Make sure branch != main branch

if [ "$branch" = "main" ]; then
    echo "You are on the main branch. Commit blocked."
    exit 1
fi

exit 0

# Make sure branch name starts will allowed prefixes

PREFIXES="feat/ fix/ doc/ chore/ refactor/ test/"

for prefix in $PREFIXES; do
    case $branch in
        $prefix*)
            exit 0
            ;;
    esac
done

echo "Commit blocked: Branch name must start with one of the following prefixes: $PREFIXES"
exit 1
