name: Create Release and Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release"
        required: true
        default: "0.1.0"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create tag
        id: tag_step
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release version v${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          body: "Release of nova-sdk version v${{ github.event.inputs.version }}"

      - name: Go to module directory
        run: |
          cd go
          go mod tidy
