name: Run Go Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  ETH_RPC_ENDPOINT: ${{ secrets.ETH_RPC_ENDPOINT }}
  OPT_RPC_ENDPOINT: ${{ secrets.OPT_RPC_ENDPOINT }}
  TEST_ADDRESS: ${{ secrets.TEST_ADDRESS }}
  TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Get dependencies
        run: go mod tidy
        working-directory: go

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install solc
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc

      - name: Add go/bin to PATH
        run: export PATH=$HOME/go/bin:$PATH

      - name: Install abigen
        run: |
          go install github.com/ethereum/go-ethereum/cmd/abigen@latest

      - name: Compile Solidity artifacts
        run: make compile
        working-directory: go

      - name: Start Anvil
        run: |
          nohup anvil --fork-url $OPT_RPC_ENDPOINT &
        working-directory: go

      - name: Update OPT_RPC_ENDPOINT
        run: |
          echo "OPT_RPC_ENDPOINT=http://localhost:8545" >> $GITHUB_ENV

      - name: Set initial balance for test address
        run: |
          curl http://localhost:8545 -X POST -H "Content-Type: application/json" \
            --data '{"method":"anvil_setBalance","params":["'"$TEST_ADDRESS"'", "0x56BC75E2D63100000"],"id":1,"jsonrpc":"2.0"}'
        working-directory: go

      - name: Run tests
        run: make test
        working-directory: go
